//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaPortal.LogoManager.ChannelManagerService {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChannelType", Namespace="http://schemas.datacontract.org/2004/07/ChannelManager")]
    public enum ChannelType : byte {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Tv = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Radio = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ChannelManagerService.IChannelManager")]
    public interface IChannelManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChannelManager/GetLogos", ReplyAction="http://tempuri.org/IChannelManager/GetLogosResponse")]
        System.Collections.Generic.Dictionary<string, string> GetLogos(string[] channelsNames, MediaPortal.LogoManager.ChannelManagerService.ChannelType type, string regionCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChannelManager/GetLogos", ReplyAction="http://tempuri.org/IChannelManager/GetLogosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> GetLogosAsync(string[] channelsNames, MediaPortal.LogoManager.ChannelManagerService.ChannelType type, string regionCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChannelManagerChannel : MediaPortal.LogoManager.ChannelManagerService.IChannelManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChannelManagerClient : System.ServiceModel.ClientBase<MediaPortal.LogoManager.ChannelManagerService.IChannelManager>, MediaPortal.LogoManager.ChannelManagerService.IChannelManager {
        
        public ChannelManagerClient() {
        }
        
        public ChannelManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChannelManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChannelManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChannelManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.Dictionary<string, string> GetLogos(string[] channelsNames, MediaPortal.LogoManager.ChannelManagerService.ChannelType type, string regionCode) {
            return base.Channel.GetLogos(channelsNames, type, regionCode);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> GetLogosAsync(string[] channelsNames, MediaPortal.LogoManager.ChannelManagerService.ChannelType type, string regionCode) {
            return base.Channel.GetLogosAsync(channelsNames, type, regionCode);
        }
    }
}
